name: Run tests with `uv`

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main

jobs:
  uv-test:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install `uv`
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --all-extras --dev
        # run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest

#
